services:
  # Backend API Service
  - type: web
    name: fullstack-todo-backend
    env: node
    plan: free
    buildCommand: cd BACKEND && npm ci --only=production
    startCommand: cd BACKEND && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: FRONTEND_URL
        sync: false

  # Frontend Static Site
  - type: web
    name: fullstack-todo-frontend
    env: static
    plan: free
    buildCommand: cd FRONTEND && npm ci && npm run build
    staticPublishPath: ./FRONTEND/dist
    envVars:
      - key: VITE_BACKEND_URL
        sync: false
